version: '3.4'

services:

  lostandfound:
    restart: always
    container_name: lostandfound
    environment:
      POSTGRES_DB: lostandfound-db
      POSTGRES_USER: lostandfound-user
      POSTGRES_PASSWORD: lostandfound-password
    ports:
      - 5435:5432
    volumes:
      - data-postgres:/var/lib/postgresql/data

  adminer:
    restart: always
    container_name: adminer
    ports:
      - 8082:8080

  lostandfoundapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - 8064:8080
      - 8065:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro